### ISSUE TITLE
[Timeout] Chat timestamp incorrect

### ISSUE THREAD

**Issue by DoctorDinosaur** [sravan1946/sravan-cogs#2]
Upon timing out someone, the chat response's timestamp is wrong by 1 hour (3600), i.e. the raw <t:timestamp:f> timestamp is 3600 lower than it should be.

I.e. I find the current UTC timestamp, then mute someone for 1 minute and check the timestamp in chat. It's in the lower than the current timestamp, i.e. in the past.

I've honestly no idea why. UTC is 1 hour out from my timezone, but the code specifies UTC time.

**Comment by sravan1946** [comment]
Have pushed a push which might fix it. Try updating and check

**Comment by DoctorDinosaur** [comment]
Yep, that fixed it!
