### ISSUE TITLE
[TIMEOUT] - add by role?

### ISSUE THREAD

**Issue by CruxCraft** [sravan1946/sravan-cogs#3]
it would be nice to have the ability to timeout every user that has a specified role-id as well, instead of just by the user-id. 

This would let me automate timeouts for an entire group at once, or even put certain roles on extreme lockdown in an emergency.

thanks =]

**Comment by cool-aid-man** [comment]
In my opinion, `timeout` should be on `user IDs` just like the massban or massmute, but the bot should neglect the IDs who may have left the server by then.
Having the option to timeout on a role sounds good, but you may not want everyone to be time-outed on that role and want a few specific people to be muted. 

So, the `masstimeout` on account of **User IDs** gives you more freedom to work with, yes! It won't be the best time saving option, but it's more practical.

**Comment by CruxCraft** [comment]
> In my opinion, `timeout` should be on `user IDs` just like the massban or massmute, but the bot should neglect the IDs who may have left the server by then. Having the option to timeout on a role sounds good, but you may not want everyone to be time-outed on that role and want a few specific people to be muted.
> 
> So, the `masstimeout` on account of **User IDs** gives you more freedom to work with, yes! It won't be the best time saving option, but it's more practical.

We have a role that is similar to a "punished" role and have been manually timeouting the users - I realize there are soft-bans instead but that actually kicks the users from the server, and the timeouts are limited to 28 days. We would like users with a role to be on timeout essentially until the role is removed. We could automate timeouts so those with that role are given a 1 day time out the moment they receive the role and also automate the role getting refreshed to 1 day each night. Then the removal of the role could either have the timeout expire the following night be automated to be removed as well. It lets us create timeouts that are role-based instead.

Edit: also automating timeouts for multiple users is a LOT more long-term than just automating it by roles

**Comment by sravan1946** [comment]
added support to timeout all the users with a role :tada:

**Comment by sravan1946** [comment]
_i might also add a masstimeout command in future which takes user_ids like cool aid said_

**Comment by CruxCraft** [comment]
> added support to timeout all the users with a role tada
![2022-09-06_21-23](https://user-images.githubusercontent.com/56696312/188788358-699c4b63-320f-4dd2-a562-3a041a32075d.png)
Worked splendidly! Thank you so much!!
