### ISSUE TITLE
Perform - Toggle Action Counts

### ISSUE THREAD

**Issue by FireFtw** [sravan1946/sravan-cogs#31]
While the stats are fun to look at, the total added to every single image just adds visual clutter in my opinion. Is it possible to get a toggle for it?

**Comment by sravan1946** [comment]
Are you talking about the stats in the embed footer?

**Comment by FireFtw** [comment]
Yeah, the little counter at the bottom of the returned images.

**Comment by sravan1946** [comment]
Have been added to the repo

**Comment by FireFtw** [comment]
> Have been added to the repo

Appreciate it!
